### ISSUE TITLE
Install as dependency

### ISSUE THREAD

**Issue by brno32** [nicolas1bruno/multipart-data-apex-request#1]
Apex newbie here. Thanks _so_ much for sharing this code! I was struggling with this as I've never constructed a multipart form data request myself since more feature-rich http clients are available in the other languages I've worked with.

Question, I had to pretty much copy and paste this code into my sfdx project. In this world, is there anything for packaging and installing dependencies, and could this class be moved to that?

e.g., when I'm working on node servers, I run `npm install axios` and I have it. If nothing like that exists for apex, could this could be packaged into a Salesforce package so that I could list it as a dependency in my sfdx repo?

**Comment by nicolas1bruno** [comment]
Hi @brno32, thanks for your feedback

As far as I know the only tool that is available right now are packages. 
Have something like npm would be really helpful altho. 

But feel free to copy and paste and use on your on project

**Comment by brno32** [comment]
Got it. Do you mind if I make a PR with some tests? I want to use this code and will need to have tests for it so my code coverage doesn't drop. I'm happy to commit it back to the repo if welcome

**Comment by nicolas1bruno** [comment]
Of Course, feel free to contribute, appreciated

**Comment by brno32** [comment]
https://github.com/nicolas1bruno/multipart-data-apex-request/pull/3

These tests gave it 95% coverage

**Comment by brno32** [comment]
Thanks for merging my tests! Would you be willing to publish this as an unmanaged packaged?
